CREATE TABLE ARVORE (
    LATITUDE DECIMAL(10, 8),
    LONGITUDE DECIMAL(11, 8),
    ESPECIE NVARCHAR2(255),
    FOTO NVARCHAR2(1024),
    PONTO_REFERENCIA NVARCHAR2(511),
    DESCRICAO NVARCHAR2(511),
    IDADE NUMBER,
    NIVEL_RISCO NVARCHAR2(6),
    RESPONSAVEL NVARCHAR2(255),
    REMOVEDOR NVARCHAR2(255),
    CONSTRAINT PK_ARVORE PRIMARY KEY (LATITUDE, LONGITUDE, ESPECIE),
    CONSTRAINT FK1_ARVORE FOREIGN KEY (RESPONSAVEL) REFERENCES ADMIN(EMAIL),
    CONSTRAINT FK2_ARVORE FOREIGN KEY (REMOVEDOR) REFERENCES ADMIN(EMAIL),
    CONSTRAINT IDADE_VALIDO CHECK (IDADE > 0),
    CONSTRAINT NIVEL_VALIDO CHECK (NIVEL_RISCO IN ('ALTO', 'MÉDIO', 'BAIXO'))
);

CREATE TABLE ADMIN (
    EMAIL NVARCHAR2(255),
    CPF CHAR(11) NOT NULL,
    NOME NVARCHAR2(255) NOT NULL,
    SENHA NVARCHAR2(255),
    CONSTRAINT PK_ADMIN PRIMARY KEY (EMAIL),
    CONSTRAINT UK_ADMIN UNIQUE (CPF),
  CONSTRAINT CPF_ADMIN CHECK (REGEXP_LIKE(CPF, '^\d{11}$'))
);

CREATE TABLE OCORRENCIA (
    LATITUDE DECIMAL(10, 8),
    LONGITUDE DECIMAL(11, 8),
    ESPECIE NVARCHAR2(255),
    DATA_HORA DATE,
    DESCRICAO NVARCHAR2(1024),
    FOTO NVARCHAR2(1024),
    NIVEL_RISCO NVARCHAR2(6),
    CONSTRAINT PK_OCORRENCIA PRIMARY KEY (LONGITUDE, LATITUDE, ESPECIE, DATA_HORA),
    CONSTRAINT FK_OCORRENCIA FOREIGN KEY (LONGITUDE, LATITUDE, ESPECIE) 
        REFERENCES ARVORE (LONGITUDE, LATITUDE, ESPECIE),
    CONSTRAINT RISCO_VALIDO CHECK (NIVEL_RISCO IN ('ALTO', 'MÉDIO', 'BAIXO'))
);

CREATE TABLE EDICOES (
    LATITUDE DECIMAL(10, 8),
    LONGITUDE DECIMAL(11, 8),
    ESPECIE NVARCHAR2(255),
    EDITOR NVARCHAR2(255),
    CONSTRAINT PK_EDICOES PRIMARY KEY (LONGITUDE, LATITUDE, ESPECIE, EDITOR),
    CONSTRAINT FK1_EDICOES FOREIGN KEY (LONGITUDE, LATITUDE, ESPECIE) 
        REFERENCES ARVORE (LONGITUDE, LATITUDE, ESPECIE),
    CONSTRAINT FK2_EDICOES FOREIGN KEY (EDITOR) REFERENCES ADMIN(EMAIL)
);